apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: 851725450272.dkr.ecr.us-east-1.amazonaws.com/shopping-site-books:096de00dc9f7db8168d03507c5cd70c19f9466ba
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books
spec:
  type: ClusterIP
  selector:
    app: books
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
